# Generated by Django 5.2 on 2026-03-11 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_file_display_name_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_token', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressbooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddressBookShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Read only'), ('write', 'Read & Write'), ('admin', 'Admin')], default='read', max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('addressbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='file.addressbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_addressbooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('color', models.CharField(default='#3498db', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_token', models.CharField(db_index=True, editable=False, max_length=128, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Read only'), ('write', 'Read & Write'), ('admin', 'Admin')], default='read', max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='file.calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_calendars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=255)),
                ('vcard_data', models.TextField()),
                ('fn', models.CharField(blank=True, max_length=500, null=True)),
                ('n', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('etag', models.CharField(db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addressbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='file.addressbook')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=255)),
                ('ical_data', models.TextField()),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('dtstart', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dtend', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('recurrence_rule', models.TextField(blank=True, null=True)),
                ('etag', models.CharField(db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='file.calendar')),
            ],
        ),
        migrations.AddIndex(
            model_name='addressbook',
            index=models.Index(fields=['owner', 'name'], name='addressbook_owner_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addressbook',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='addressbookshare',
            unique_together={('addressbook', 'user')},
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['owner', 'name'], name='calendar_owner_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='calendarshare',
            unique_together={('calendar', 'user')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['addressbook', 'fn'], name='contact_addressbook_fn_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['addressbook', 'uid'], name='contact_addressbook_uid_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('addressbook', 'uid')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['calendar', 'dtstart'], name='event_calendar_start_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['calendar', 'uid'], name='event_calendar_uid_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('calendar', 'uid')},
        ),
    ]
