# Generated by Django 5.2 on 2026-03-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_email_emailattachment_mailbox_email_mailbox_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbox',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='mailbox',
            name='system',
            field=models.BooleanField(default=False),
        ),
    ]
