# Generated by Django 5.2 on 2026-03-15 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_emailsignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedMailboxMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Read only'), ('write', 'Read & Write'), ('admin', 'Admin')], default='read', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mailbox',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SharedMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email_alias', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shared_mailboxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mailbox',
            name='shared_mailbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='file.sharedmailbox'),
        ),
        migrations.AddConstraint(
            model_name='mailbox',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'name'), name='unique_owner_mailbox'),
        ),
        migrations.AddConstraint(
            model_name='mailbox',
            constraint=models.UniqueConstraint(condition=models.Q(('shared_mailbox__isnull', False)), fields=('shared_mailbox', 'name'), name='unique_shared_mailbox'),
        ),
        migrations.AddField(
            model_name='sharedmailboxmembership',
            name='shared_mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='file.sharedmailbox'),
        ),
        migrations.AddField(
            model_name='sharedmailboxmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_mailbox_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sharedmailboxmembership',
            unique_together={('shared_mailbox', 'user')},
        ),
    ]
