# Generated by Django 5.2 on 2026-03-20 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_sharedmailboxmembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_folder', to='file.contact')),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_folder_ref', to='file.folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'contact')},
            },
        ),
    ]
