# Generated by Django 5.2 on 2026-03-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_contactgroup_contactgroupfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='addressbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='file.addressbook'),
        ),
    ]
