# Generated by Django 5.2 on 2026-03-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0014_contact_group_addressbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('needs-action', 'Needs Action'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative')], default='needs-action', max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='file.event')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
    ]
